// <auto-generated />
namespace PassRegistration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddPassRegistrations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPassRegistrations));
        
        string IMigrationMetadata.Id
        {
            get { return "201712062021403_AddPassRegistrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
